### ISSUE TITLE
PLUGIN STOLEN AND AGAINST THE LICENSE

### ISSUE THREAD

**Issue by remotevase** [CristaudoORG/Gladiators#1]
# THIS PLUGIN WAS COPIED FROM SURVIVALGAMESV3 BY IMAGICALGAMER. 

# YOU HAVE MODIFIED IT AND APPARENTLY REDISTRIBUTED IT. 

# THAT IS AGAINST THE LICENSE OF THE PLUGIN. 

# I WILL BE CONSTANTLY WATCHING THIS BRANCH.

# IF YOU DO NOT DELETE THIS BRANCH ALONG WITH ALL OTHER PUBLIC VERSIONS OF THE PLUGIN, COMPLAINTS WILL BE FILED AGAINST YOU.

**Comment by CristaudoORG** [comment]
ahahahaahah

**Comment by remotevase** [comment]
I am not hooking, this could cost you over 10,000 USDollars

**Comment by CristaudoORG** [comment]
hahahahaaha yes yes

**Comment by GladiatorMine-Owner** [comment]
u nvr filed any agianst me so shyut up fucker

**Comment by remotevase** [comment]
Actually, @GladiatorMine-Owner I am part of the imagicalMine team, meaning that we have already filed charges against you and your company for stealing plugins. This is just another to add to the list

**Comment by CristaudoORG** [comment]
AHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAH YOU HAVE A 10 YEAR?
